# Generated by Django 3.2.9 on 2022-03-23 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CFD_ML', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frauddetectcount',
            name='DateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
